export default [{
  name: 'Model S',
  tagline: 'Starting at $69,420',
  image: require('../../assets/images/ModelS.jpeg'),
  coLink: 'https://www.tesla.com/models/design#overview',
  viLink: 'https://www.tesla.com/inventory/new/ms?arrangeby=relevance&zip=90003&range=200',
  typ:'car',
}, {
  name: 'Model 3',
  tagline: 'Order Online for',
  taglineCTA: 'Touchless Delivery',
  image: require('../../assets/images/Model3.jpeg'),
  coLink: 'https://www.tesla.com/model3/design#overview',
  viLink: 'https://www.tesla.com/inventory/new/m3?arrangeby=relevance&zip=90003&range=200',
  typ:'car',
}, {
  name: 'Model X',
  tagline: 'Order Online for',
  taglineCTA: 'Touchless Delivery',
  image: require('../../assets/images/ModelX.jpeg'),
  coLink: 'https://www.tesla.com/modelx/design#overview',
  viLink: 'https://www.tesla.com/inventory/new/mx?arrangeby=relevance&zip=90003&range=200',
  typ:'car',
}, {
  name: 'Model Y',
  tagline: 'Order Online for',
  taglineCTA: 'Touchless Delivery',
  image: require('../../assets/images/ModelY.jpeg'),
  coLink: 'https://www.tesla.com/modely/design#overview',
  viLink: 'https://www.tesla.com/inventory/new/my?arrangeby=relevance&zip=90003&range=200',
  typ:'car',
}, {
  name: 'Solar Panels',
  tagline: 'Order Online for',
  taglineCTA: 'Touchless Delivery',
  image: require('../../assets/images/SolarPanels.jpeg'),
  coLink: 'https://www.tesla.com/energy/design',
  viLink: 'https://www.tesla.com/solarpanels',
  typ:'solar',
}, {
  name: 'Solar Roof',
  tagline: 'Order Online for',
  taglineCTA: 'Touchless Delivery',
  image: require('../../assets/images/SolarRoof.jpeg'),
  coLink: 'https://www.tesla.com/energy/design',
  viLink: 'https://www.tesla.com/solarroof',
  typ:'solar',
},];
